### ISSUE TITLE
Service in docker issue

### ISSUE THREAD

**Issue by ralphQi** [micro/monitor-srv#5]
If I put my service into docker, monitor-srv will lose stat connection.

Service and monitor-srv use the same "RegistryAddr" value.

**Comment by ralphQi** [comment]
I am confused about that how do monitor-srv and micro service connect to each other?through consul?

**Comment by asim** [comment]
Please refer to the diagram in the readme. You can see that services publish stats and the monitor-srv subscribes to them. The default broker makes use of consul to find topics. 

There's currently no active development on this project.

**Comment by ralphQi** [comment]
Thank you

**Comment by ralphQi** [comment]
I have solved the problem.

If you do not specify "registry_address" for the services which runs in docker, It won't be able to find the right consul server(I think it's using localhost:8500) to send health check data.

Actually I have already specify "registry_address" in my service code, but it seems that it dose not  work for monitor but only for service itself.

Thank you again!
